site_name: Pim Wiki
site_url: https://wiki.pim.gr.jp/
repo_url: https://github.com/shimane-u-pim/wiki
repo_name: shimane-u-pim/wiki
edit_uri: edit/master/docs/
site_author: 島根大学ものづくり部 Pim, Pim Wiki Authors
copyright: Copyright (c) 2024 島根大学ものづくり部 Pim, Pim Wiki Authors
validation:
  nav:
   omitted_files: info
   not_found: warn
   absolute_links: warn
  links:
    not_found: warn
    # Should enable after mkdocs version 1.6
    #anchors: warn
    absolute_links: warn
    unrecognized_links: warn
docs_dir: docs
site_dir: site
strict: true
plugins:
  - search:
      enabled: false
      lang: 'ja'
  - minify:
      minify_html: true
      # minify_js: true
      # minify_css: true
      # cache_safe: true
      htmlmin_opts:
        remove_empty_space: true
        reduce_boolean_attributes: true
        remove_comments: true
  - mermaid2
  - callouts:
      aliases: false
  - privacy:
      enabled: false
      #links: true
      #links_attr_map:
      #  target: _blank
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  icon:
    admonition:
      note: octicons/info-16
      tip: octicons/light-bulb-16
      important: octicons/report-16
      warning: octicons/alert-16
      caution: octicons/stop-16
    repo: fontawesome/brands/github
  logo: _assets/logo/pimlogo.svg
  language: ja
  palette:
    primary: red
  features:
    - content.action.edit

extra_css: 
  - "_assets/css/admonitions.css"