site_name: Pim Wiki
site_url: https://wiki.pim.gr.jp/
repo_url: https://github.com/shimane-u-pim/wiki
repo_name: GitHub
site_author: 島根大学ものづくり部 Pim, Pim Wiki Authors
copyright: Copyright (c) 2024 島根大学ものづくり部 Pim, Pim Wiki Authors
validation:
  nav:
   omitted_files: info
   not_found: warn
   absolute_links: warn
  links:
    not_found: warn
    # Should enable after mkdocs version 1.6
    #anchors: warn
    absolute_links: warn
    unrecognized_links: warn
docs_dir: docs
site_dir: site
strict: true